package org.example.Enum;

public enum Type {
    HAIKU, LIMERICK, SENRYU, TANKA, SONNET, VILLANELLE, ACROSTIC, ELEGY, ODE, GHAZAL, SESTINA, PANTOUM, TERZARIMA, TRIOLET, RONDEL, RONDEAU, BALLAD, EPIC, FREEVERSE, LYRIC, NARRATIVE, PROSE, RHYMEDVERSE, BLANKVERSE, CONCRETE, FOUND, LIGHT, VISUAL
}
